# Generated by Django 4.1.3 on 2022-12-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=200)),
                ('nota_final', models.IntegerField()),
            ],
        ),
    ]
